### ISSUE TITLE
[Feature]Implement forgot password flow

### ISSUE THREAD

**Issue by lakshitaverma** [prashantacharya/idea-submission#1]

**Comment by prashantacharya** [comment]
I was occupied in something else. Thanks to @sagar608, the feature is now live.

**Comment by lakshitaverma** [comment]
Hi Guys, thanks for implementing the feature. Shouldn't we create a UI for this idea as well?? I am up for this. We can use ReactJs for it. Anybody up for it??

**Comment by lakshitaverma** [comment]
Getting this - {
    "status": "success",
    "message": "Your password has been successfully changed"
} after changing password. @sagar608 
But not able to login with email and new password. Did you check this flow??

**Comment by lakshitaverma** [comment]
@sagar608 With new password, getting this - {
    "status": "Error",
    "message": "Email or password doesn't match"
}

**Comment by sagar608** [comment]
@lakshitaverma  I didn't checked that, let me check it, it should work if the password is getting changed.

**Comment by sagar608** [comment]
@lakshitaverma  Thank you for the issue, i was able to find the bug, and fixed it now it works fine.
